# Generated by Django 4.1.3 on 2022-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bureau", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
