# Generated by Django 4.1.3 on 2022-12-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bureau", "0002_alter_newspaper_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ("published_date",)},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("name",)},
        ),
    ]
